### ISSUE TITLE
Install talib and forex.analytics fails (solved)

### ISSUE THREAD

**Issue by conradhagemans** [carlos8f/zenbot#1765]
### System information
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:

Linux Ubuntu 18.04

- **Zenbot version** (commit ref, or version):
4.1.0

### Describe the problem
I have seen many post from people struggling to get Zenbot installed. It took me also some time and I have some experience with Linux.

The installation kept on crashing. I am using a complete untouched, fresh installed Ubuntu 18.04 machine.

Before you run:
**npm install**
you have to make some changes.

**1.**
Change the package.json file (use VI or VIM or any other editor)
Search for the line with:
`"forex.analytics": "github:mkmarek/forex.analytics#7bc278987700d4204e959af17de61495941d1a14",
`
change it into:

`"forex.analytics": "^0.0.15",
`
save the file.

**2.**
The Talib package fails to compile because a missing compiler that is part of Python. run the command:

`apt install python-dev
`

**3.**

Now run 

`npm install
`
I was still missing an other package:

` npm install tulind
`

**Additional:**
If you already ran the npm install script and it crashed (or did not finish) you also have to remove the forex.analytics directory manualy before running it again:

`rm -R node_modules/forex.analytics
`

**Comment by trivalik** [comment]
To fix it also for windows:

replace it instead with:
    "forex.analytics": "github:trivalik/forex.analytics#1d3b9fe24f7b4571269c3656925d56347439ef6c",

@DeviaVir: best would be that you fork that repository
and remove talib from package.json, since it is part of forex.analytics.

**Comment by TheRinger** [comment]
zenbot$ npm update
npm ERR! path /home/alien/apps/zenbot/node_modules/forex.analytics
npm ERR! code EISGIT
npm ERR! git /home/alien/apps/zenbot/node_modules/forex.analytics: Appears to be a git repo or submodule.
npm ERR! git     /home/alien/apps/zenbot/node_modules/forex.analytics
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/$USER/.npm/_logs/2019-01-24T03_18_18_910Z-debug.log

Best way I've found to remove this annoyance is adding
'sudo rm -rf node_modules/forex.analytics/{.git,.travis.yml}'
to zenbot's update.sh file, after the checkout, I'm not as familiar with how that can be done as part of the npm script hook 
but .git has always required me to superuser in order to rm git project directories

I run linuxbrew so not sure if this works for anyone else but to stop the node-gyp talib build fail I just ended up installing talib and node-gyp globally with 'npm install -g node-gyp && npm install -g talib && npm install forex.analytics -g' 
Ishould be possible without global (-g) flag but havent confirmed

**Comment by TheRinger** [comment]
zenbot$ `npm update`
**npm ERR! path /home/hidden/apps/zenbot/node_modules/forex.analytics
npm ERR! code EISGIT
npm ERR! git /home/hidden/apps/zenbot/node_modules/forex.analytics: Appears to be a git repo or submodule.
npm ERR! git /home/hidden/apps/zenbot/node_modules/forex.analytics
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.

npm ERR! A complete log of this run can be found in:
npm ERR! /home/hidden/.npm/_logs/2019-01-24T03_18_18_910Z-debug.log**

Best way I've found to remove this annoyance is adding


**`sudo rm -rf node_modules/forex.analytics/{.git,.travis.yml}`**

I also use a hook to install tulind this way instead of letting forex.analytics do it which seems to try an older link that fails to download.

npm install tulind --build-from-source

to zenbot's update.sh file, after the checkout, I'm not as familiar with how that can be done as part of the npm script hook
but .git has always required me to superuser in order to rm git project directories

then there is this 

node-pre-gyp WARN Using request for node-pre-gyp https download 
node-pre-gyp WARN Tried to download(404): https://tulipnode.s3.amazonaws.com/tulind/v0.8.13/Release/tulind-v0.8.13-node-v57-linux-x64.tar.gz 
node-pre-gyp WARN Pre-built binaries not found for tulind@0.8.13 and node@8.15.0 (node-v57 ABI, glibc) (falling back to source compile with node-gyp) 

possibly fork the forex.analytics repo change call for talind to install by way of 
 npm install tulind --build-from-source
 forex.analytics hasn't been active on github in nearly 2 years

**Comment by BAKFR** [comment]
The tulind problem is related to TulipCharts/tulipnode#48 

A bug in node-pre-gyp cause the `tulind` build to be executed twice at the same time (for NodeJs >= 10).

**Comment by hankyupark** [comment]
> ### System information
> * **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**:
> 
> Linux Ubuntu 18.04
> 
> * **Zenbot version** (commit ref, or version):
>   4.1.0
> 
> ### Describe the problem
> I have seen many post from people struggling to get Zenbot installed. It took me also some time and I have some experience with Linux.
> 
> The installation kept on crashing. I am using a complete untouched, fresh installed Ubuntu 18.04 machine.
> 
> Before you run:
> **npm install**
> you have to make some changes.
> 
> **1.**
> Change the package.json file (use VI or VIM or any other editor)
> Search for the line with:
> `"forex.analytics": "github:mkmarek/forex.analytics#7bc278987700d4204e959af17de61495941d1a14", `
> change it into:
> 
> `"forex.analytics": "^0.0.15", `
> save the file.
> 
> **2.**
> The Talib package fails to compile because a missing compiler that is part of Python. run the command:
> 
> `apt install python-dev `
> 
> **3.**
> 
> Now run
> 
> `npm install `
> I was still missing an other package:
> 
> `npm install tulind`
> 
> **Additional:**
> If you already ran the npm install script and it crashed (or did not finish) you also have to remove the forex.analytics directory manualy before running it again:
> 
> `rm -R node_modules/forex.analytics `

It works for me.
@conradhagemans Thank you so much!

**Comment by yellowgh0st** [comment]
Unable to build also on macOS where this workaround doesn't work.
The issue is probably the same. Just scrypt compilation is failing too.

**Comment by jorisw** [comment]
Building on macOS 10.14.6, with node 10.16.3, indeed, fails on the following error:

```
[...]
building talib functions...
> forex.analytics@0.0.15 postinstall ./node_modules/forex.analytics
> node-gyp configure && node-gyp build
[...]
  CXX(target) Release/obj.target/analytics/src/functions/getIndicatorData.o
  CXX(target) Release/obj.target/analytics/src/functions/getMarketStatus.o
  CXX(target) Release/obj.target/analytics/src/functions/getTrades.o
  SOLINK_MODULE(target) Release/analytics.node
clang: error: no such file or directory: '../lib/ta-lib/lib/libta_abstract_csr.a'
clang: error: no such file or directory: '../lib/ta-lib/lib/libta_func_csr.a'
clang: error: no such file or directory: '../lib/ta-lib/lib/libta_libc_csr.a'
make: *** [Release/analytics.node] Error 1
```

A `brew install ta-lib`, as suggested [here](https://stackoverflow.com/a/43314341/1336408), didn't help.

**Comment by yellowgh0st** [comment]
@jorisw check this #1934 
Checkout my branch in order to build.
While you also have to manually remove:

- /commands/train.js
- /extensions/strategies/forex_analytics

Until forex_analytics become fixed.

**Comment by yellowgh0st** [comment]
I have just pushed #1937 
as one possible solution.

Builds well.

@jorisw Check this out if you don't mind about forex_analytics.

**Comment by jorisw** [comment]
Thanks, removing forex and commenting its use out of train.js is what I ended up doing. Runs on Mac now.

**Comment by yellowgh0st** [comment]
Going to look if I can fix forex lib later.
